### ISSUE TITLE
After setup

### ISSUE THREAD

**Issue by saashqdev** [kgierke/terraform-hcloud-talos-cluster#1]
Hi:
I have a fresh new Hetzner / Talos setup completed. I've installed cert-manager and ingress-nginx - now what? :-) How do I login to a web dashboard to start doing stuff? I'm going to take a peek at Cozystack. Cheers, Dave

**Comment by kgierke** [comment]
Hi, thats totally up to you, as this Module is only intended to get a Kubernetes Cluster up and running. Personally I use [Lens](https://k8slens.dev) to have a GUI for inspecting the Cluster, but there a for sure many alternatives.

I'm going to close this issue, as this is not really an issue with the module though :)
